import fixHeight from './includes/fixHeight.js';
import mobileNav from './includes/mobileNav.js';
import scrollToId from './includes/scrollToId.js';
import initTabs from './includes/initTabs.js';
import modal from './includes/modal.js';
import langDropdown from './includes/langDropdown.js';
import checkoutFormValidation from './includes/checkoutFormValidation.js';
import promoFormValidation from './includes/promoFormValidation.js';
import feedbackFormValidation from './includes/feedbackFormValidation.js';
import inputFile from './includes/inputFile.js';
import topSlider from './includes/topSlider.js';
import footerMenu from './includes/footerMenu.js';
import numbersInput from './includes/numbersInput.js';
import select from './includes/select.js';
import closeAlert from './includes/closeAlert.js';
import photoSwipe from './includes/photoSwipe.js';
import phoneMask from './includes/phoneMask.js';
import deliveryRadio from './includes/deliveryRadio.js';
import '../sass/main.sass';


fixHeight();
mobileNav();
scrollToId();
initTabs();
modal();
langDropdown();
checkoutFormValidation();
promoFormValidation();
feedbackFormValidation();
inputFile();
topSlider();
footerMenu();
numbersInput();
select();
closeAlert();
photoSwipe();
phoneMask();
deliveryRadio();